const allMoviesData = [
    { 
        id: 1,
        title: "Spy x Family Code: White", 
        year: "2023", 
        rating: "9.1/10",
        desc: "Perjalanan liburan keluarga Forger ke wilayah Frigis agar Anya bisa mencicipi makanan khas untuk memenangkan kompetisi memasak di Akademi Eden, namun liburan itu berubah menjadi misi penyelamatan dunia saat Anya menemukan rahasia yang mengancam perdamaian.",
        genres: ["Anime", "Action", "Comedy", "Family"], 
        poster: "./Asset/PosterFilm/Spy_×_Family_Code_White_movie_poster.png",
        background: "./Asset/BackgroundFilm/SpyxFamilyBackground.jpeg",
        trailer: "./Asset/Trailer/SpyXFamily_Trailer.mp4" 
    },
    { 
        id: 2,
        title: "Haikyu!! The Dumpster Battle", 
        year: "2024", 
        rating: "8.8/10",
        desc: "Meskipun menghadapi persaingan yang ketat, tim voli SMA Karasuno berhasil melaju dari babak penyisihan turnamen Harutaka di prefektur Miyagi untuk mencapai babak ketiga.",
        genres: ["Anime", "Sports", "Drama"], 
        poster: "./Asset/PosterFilm/haikyu-the-dumpster-battle.jpeg",
        background: "./Asset/BackgroundFilm/haikyu-the-dumpster-battleL.jpeg",
        trailer: "./Asset/Trailer/HAIKYU!! THE DUMPSTER BATTLE 🏐 - Cinépolis Indonesia (1).mp4"
    },
    { 
        id: 3,
        title: "Agak Laen", 
        year: "2024", 
        rating: "7.9/10",
        desc: "Empat sekawan penjaga rumah hantu yang sepi pengunjung dan hampir bangkrut, yang akhirnya menemukan keuntungan tak terduga saat salah satu pengunjung meninggal karena kaget, lalu mereka menyembunyikan mayatnya dan rumah hantu mereka jadi viral.",
        genres: ["Comedy", "Horror"], 
        poster: "./Asset/PosterFilm/Agak_Laen_(2024).jpg",
        background: "./Asset/BackgroundFilm/Agak_Laen_(2024)L.jpeg",
        trailer: "./Asset/Trailer/Agak Laen Trailer.mp4" 
    },
    {
        id: 4,
        title: "Zootopia", 
        year: "2016", 
        rating: "8.0/10",
        desc: "Di kota hewan antropomorfik, Judy Hopps, seekor kelinci polisi pemula, harus bekerja sama dengan rubah penipu bernama Nick Wilde untuk memecahkan misteri konspirasi yang mengancam keharmonisan kota.",
        genres: ["Adventure", "Comedy", "Family"],
        poster: "./Asset/PosterFilm/Zootopia.jpg",
        background: "./Asset/BackgroundFilm/ZootopiaL.jpg",
        trailer: "./Asset/Trailer/ZootopiaTrailer.mp4"
    },
    {
        id: 5,
        title: "Avengers: Endgame", 
        year: "2019", 
        rating: "8.4/10",
        desc: "Setelah peristiwa Thanos yang melenyapkan setengah populasi alam semesta, para Avengers yang tersisa harus berkumpul kembali dan melakukan perjalanan waktu untuk membatalkan tindakan Thanos demi memulihkan keteraturan alam semesta.",
        genres: ["Action", "Adventure", "Sci-Fi"],
        poster: "./Asset/PosterFilm/endgame.jpeg",
        background: "./Asset/BackgroundFilm/EndgameL.jpg",
        trailer: "./Asset/Trailer/Endgametrailer.mp4"
    },

    {
        id: 6,
        title: "A Man Called Otto",
        director: "Marc Forster",
        year: "2022",
        rating: "7.5/10",
        desc: "Otto is a grump who's given up on life following the loss of his wife and wants to end it all. When a young family moves in nearby, he meets his match in quick-witted Marisol.",
        genres: ["Comedy"],
        poster: "resources/aManCalledOtto.jpg",
        background: "resources/aManCalledOttoL.jpg",
        trailer: ""
    },
    {
        id: 7,
        title: "Bullet Train Explosion",
        director: "Shinji Higuchi",
        year: "2025",
        rating: "N/A",
        desc: "Five assassins aboard a fast-moving bullet train find out their missions have something in common.",
        genres: ["Action"],
        poster: "resources/bulletTrainExplosion.jpg",
        background: "resources/bulletTrainExplosionL.jpg",
        trailer: ""
    },
    {
        id: 8,
        title: "The Wild Robot",
        director: "Chris Sanders",
        year: "2024",
        rating: "8.3/10",
        desc: "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island.",
        genres: ["Adventure"],
        poster: "resources/theWildRobot.jpg",
        background: "resources/theWildRobotL.jpg",
        trailer: ""
    },
    {
        id: 9,
        title: "The Truman Show",
        director: "Peter Weir",
        year: "1998",
        rating: "8.2/10",
        desc: "An insurance salesman discovers his whole life is actually a reality TV show.",
        genres: ["Drama"],
        poster: "resources/theTrumanShow.jpg",
        background: "resources/theTrumanShowL.jpg",
        trailer: ""
    },
    {
        id: 10,
        title: "Why Didn't I Tell You a Million Times",
        director: "Fuminori Kaneko",
        year: "2023",
        rating: "7.9/10",
        desc: "Drama Jepang tentang cinta dan penyesalan.",
        genres: ["J-Drama"],
        poster: "resources/wdityamt.jpg",
        background: "resources/wdityamtL.jpg",
        trailer: ""
    },
    {
        id: 11,
        title: "The Green Mile",
        director: "Frank Darabont",
        year: "1999",
        rating: "8.6/10",
        desc: "Kisah menyentuh hati di penjara Death Row.",
        genres: ["Mystery"],
        poster: "resources/theGreenMile.jpg",
        background: "resources/theGreenMileL.jpg",
        trailer: ""
    },
    {
        id: 12,
        title: "Nightcrawler",
        director: "Dan Gilroy",
        year: "2014",
        rating: "7.8/10",
        desc: "Thriller jurnalisme kriminal yang gelap.",
        genres: ["Drama"],
        poster: "resources/nightcrawler.jpg",
        background: "resources/nightcrawlerL.jpg",
        trailer: ""
    },
    {
        id: 13,
        title: "House",
        director: "David Shore",
        year: "2004",
        rating: "8.7/10",
        desc: "Serial medis tentang dokter jenius yang antisosial.",
        genres: ["Mystery"],
        poster: "resources/house.jpg",
        background: "resources/houseL.jpg",
        trailer: ""
    },
    {
        id: 14,
        title: "It",
        director: "Andy Muschietti",
        year: "2017",
        rating: "7.3/10",
        desc: "Teror badut Pennywise menghantui anak-anak kota Derry.",
        genres: ["Horror"],
        poster: "resources/it.jpg",
        background: "resources/itL.jpg",
        trailer: ""
    },
    {
        id: 15,
        title: "The Terminal",
        director: "Steven Spielberg",
        year: "2004",
        rating: "7.4/10",
        desc: "Seorang turis terjebak di bandara JFK karena negaranya mengalami kudeta.",
        genres: ["Comedy"],
        poster: "resources/theTerminal.jpg",
        background: "resources/theTerminalL.jpg",
        trailer: ""
    },
    {
        id: 16,
        title: "Lost",
        director: "J.J. Abrams",
        year: "2004",
        rating: "8.3/10",
        desc: "Korban selamat kecelakaan pesawat terdampar di pulau misterius.",
        genres: ["Mystery"],
        poster: "resources/lost.jpg",
        background: "resources/lostL.jpg",
        trailer: ""
    },
    {
        id: 17,
        title: "District 9",
        director: "Neill Blomkamp",
        year: "2009",
        rating: "7.9/10",
        desc: "Alien terdampar di Bumi dan dipaksa tinggal di kondisi kumuh.",
        genres: ["Action"],
        poster: "resources/district9.jpg",
        background: "resources/district9L.jpg",
        trailer: ""
    },
    {
        id: 18,
        title: "Everything Everywhere All At Once",
        director: "Daniels",
        year: "2022",
        rating: "7.8/10",
        desc: "Seorang imigran Tionghoa terseret petualangan gila melintasi multiverse.",
        genres: ["Action"],
        poster: "resources/eeaao.jpg",
        background: "resources/eeaaoL.jpg",
        trailer: ""
    },
    {
        id: 19,
        title: "The Dark Knight",
        director: "Christopher Nolan",
        year: "2008",
        rating: "9.0/10",
        desc: "Batman menghadapi kekacauan yang disebar oleh Joker.",
        genres: ["Action"],
        poster: "resources/theDarkKnight.jpg",
        background: "resources/theDarkKnightL.jpg",
        trailer: ""
    },
    {
        id: 20,
        title: "The Matrix",
        director: "The Wachowskis",
        year: "1999",
        rating: "8.7/10",
        desc: "Hacker Neo menemukan kebenaran tentang realitas simulasinya.",
        genres: ["Action"],
        poster: "resources/theMatrix.jpg",
        background: "resources/theMatrixL.jpg",
        trailer: ""
    },
    {
        id: 21,
        title: "Cowboy Bebop",
        director: "Shinichirō Watanabe",
        year: "1998",
        rating: "8.9/10",
        desc: "Petualangan pemburu hadiah luar angkasa di masa depan.",
        genres: ["Adventure"],
        poster: "resources/cowboyBebop.jpg",
        background: "resources/cowboyBebopL.jpg",
        trailer: ""
    },
    {
        id: 22,
        title: "Indiana Jones and The Last Crusade",
        director: "Steven Spielberg",
        year: "1989",
        rating: "8.2/10",
        desc: "Indy mencari ayahnya yang hilang saat mencari Cawan Suci.",
        genres: ["Adventure"],
        poster: "resources/indianaJonesAndTheLastCrusade.jpg",
        background: "resources/indianaJonesAndTheLastCrusadeL.jpg",
        trailer: ""
    },
    {
        id: 23,
        title: "Wall-E",
        director: "Andrew Stanton",
        year: "2008",
        rating: "8.4/10",
        desc: "Robot pemadat sampah memulai perjalanan luar angkasa yang menentukan nasib umat manusia.",
        genres: ["Adventure"],
        poster: "resources/wallE.jpg",
        background: "resources/wallEL.jpg",
        trailer: ""
    },
    {
        id: 24,
        title: "Up",
        director: "Pete Docter",
        year: "2009",
        rating: "8.3/10",
        desc: "Pria tua menerbangkan rumahnya dengan balon ke Paradise Falls.",
        genres: ["Adventure"],
        poster: "resources/up.jpg",
        background: "resources/upL.jpg",
        trailer: ""
    },
    {
        id: 25,
        title: "Free Guy",
        director: "Shawn Levy",
        year: "2021",
        rating: "7.1/10",
        desc: "NPC video game menyadari bahwa dia hidup di dalam game.",
        genres: ["Comedy"],
        poster: "resources/freeGuy.jpg",
        background: "resources/freeGuyL.jpg",
        trailer: ""
    },
    {
        id: 26,
        title: "The Intouchables",
        director: "Olivier Nakache",
        year: "2011",
        rating: "8.5/10",
        desc: "Persahabatan unik antara bangsawan lumpuh dan pengasuhnya.",
        genres: ["Comedy"],
        poster: "resources/theIntouchables.jpg",
        background: "resources/theIntouchablesL.jpg",
        trailer: ""
    },
    {
        id: 27,
        title: "Liar Liar",
        director: "Tom Shadyac",
        year: "1997",
        rating: "6.9/10",
        desc: "Pengacara yang tidak bisa berbohong selama 24 jam.",
        genres: ["Comedy"],
        poster: "resources/liarLiar.jpg",
        background: "resources/liarLiarL.jpg",
        trailer: ""
    },
    {
        id: 28,
        title: "Whiplash",
        director: "Damien Chazelle",
        year: "2014",
        rating: "8.5/10",
        desc: "Drummer muda didorong hingga batasnya oleh instruktur yang kejam.",
        genres: ["Drama"],
        poster: "resources/whiplash.jpg",
        background: "resources/whiplashL.jpg",
        trailer: ""
    },
    {
        id: 29,
        title: "The Social Network",
        director: "David Fincher",
        year: "2010",
        rating: "7.8/10",
        desc: "Kisah berdirinya Facebook dan konflik hukum di baliknya.",
        genres: ["Drama"],
        poster: "resources/theSocialNetwork.jpg",
        background: "resources/theSocialNetworkL.jpg",
        trailer: ""
    },
    {
        id: 30,
        title: "Better Call Saul",
        director: "Vince Gilligan",
        year: "2015",
        rating: "9.0/10",
        desc: "Prekuel Breaking Bad yang mengisahkan Jimmy McGill menjadi Saul Goodman.",
        genres: ["Drama"],
        poster: "resources/betterCallSaul.jpg",
        background: "resources/betterCallSaulL.jpg",
        trailer: ""
    },
    {
        id: 31,
        title: "Scott Pilgrim vs. The World",
        director: "Edgar Wright",
        year: "2010",
        rating: "7.5/10",
        desc: "Scott harus mengalahkan 7 mantan jahat pacar barunya.",
        genres: ["Fantasy"],
        poster: "resources/scottPilgrimVsTheWorld.jpg",
        background: "resources/scottPilgrimVsTheWorldL.jpg",
        trailer: ""
    },
    {
        id: 32,
        title: "Pan's Labyrinth",
        director: "Guillermo del Toro",
        year: "2006",
        rating: "8.2/10",
        desc: "Kisah dongeng gelap berlatar Spanyol tahun 1944.",
        genres: ["Fantasy"],
        poster: "resources/pan'sLabyrinth.jpg",
        background: "resources/pan'sLabyrinthL.jpg",
        trailer: ""
    },
    {
        id: 33,
        title: "Adventure Time",
        director: "Pendleton Ward",
        year: "2010",
        rating: "8.6/10",
        desc: "Petualangan Finn manusia dan Jake anjing ajaib.",
        genres: ["Fantasy"],
        poster: "resources/adventureTime.jpg",
        background: "resources/adventureTimeL.jpg",
        trailer: ""
    },
    {
        id: 34,
        title: "Klaus",
        director: "Sergio Pablos",
        year: "2019",
        rating: "8.2/10",
        desc: "Asal usul Santa Claus dalam animasi yang indah.",
        genres: ["Fantasy"],
        poster: "resources/klaus.jpg",
        background: "resources/klausL.jpg",
        trailer: ""
    },
    {
        id: 35,
        title: "Invincible",
        director: "Robert Kirkman",
        year: "2021",
        rating: "8.7/10",
        desc: "Anak superhero terkuat di bumi mulai mengembangkan kekuatannya sendiri.",
        genres: ["Fantasy"],
        poster: "resources/invincible.jpg",
        background: "resources/invincibleL.jpg",
        trailer: ""
    },
    {
        id: 36,
        title: "Five Nights At Freddy's",
        director: "Emma Tammi",
        year: "2023",
        rating: "5.5/10",
        desc: "Penjaga keamanan malam menghadapi robot animatronik pembunuh.",
        genres: ["Horror"],
        poster: "resources/fnaf.jpg",
        background: "resources/fnafL.jpg",
        trailer: ""
    },
    {
        id: 37,
        title: "Get Out",
        director: "Jordan Peele",
        year: "2017",
        rating: "7.8/10",
        desc: "Kunjungan ke rumah pacar berubah menjadi mimpi buruk.",
        genres: ["Horror"],
        poster: "resources/getOut.jpg",
        background: "resources/getOutL.jpg",
        trailer: ""
    },
    {
        id: 38,
        title: "Mama",
        director: "Andy Muschietti",
        year: "2013",
        rating: "6.2/10",
        desc: "Dua gadis kecil diasuh oleh entitas misterius bernama Mama.",
        genres: ["Horror"],
        poster: "resources/mama.jpg",
        background: "resources/mamaL.jpg",
        trailer: ""
    },
    {
        id: 39,
        title: "Godzilla Minus One",
        director: "Takashi Yamazaki",
        year: "2023",
        rating: "8.3/10",
        desc: "Jepang pasca-perang menghadapi ancaman baru: Godzilla.",
        genres: ["Horror"],
        poster: "resources/godzillaMinusOne.jpg",
        background: "resources/godzillaMinusOneL.jpg",
        trailer: ""
    },
    {
        id: 40,
        title: "Prisoners",
        director: "Denis Villeneuve",
        year: "2013",
        rating: "8.1/10",
        desc: "Seorang ayah mengambil tindakan sendiri saat putrinya diculik.",
        genres: ["Mystery"],
        poster: "resources/prisoners.jpg",
        background: "resources/prisonersL.jpg",
        trailer: ""
    },
    {
        id: 41,
        title: "Harakiri",
        director: "Masaki Kobayashi",
        year: "1962",
        rating: "8.6/10",
        desc: "Kisah samurai klasik tentang kehormatan dan kemiskinan.",
        genres: ["Mystery"],
        poster: "resources/harakiri.jpg",
        background: "resources/harakiriL.jpg",
        trailer: ""
    },
    {
        id: 42,
        title: "Donnie Darko",
        director: "Richard Kelly",
        year: "2001",
        rating: "8.0/10",
        desc: "Remaja bermasalah dihantui oleh kelinci raksasa yang memprediksi kiamat.",
        genres: ["Thriller"],
        poster: "resources/donnieDarko.jpg",
        background: "resources/donnieDarkoL.jpg",
        trailer: ""
    },
    {
        id: 43,
        title: "The Shawshank Redemption",
        director: "Frank Darabont",
        year: "1994",
        rating: "9.3/10",
        desc: "Persahabatan dan harapan di dalam penjara seumur hidup.",
        genres: ["Thriller"],
        poster: "resources/elitis.jpg",
        background: "resources/elitisL.jpg",
        trailer: ""
    },
    {
        id: 44,
        title: "Parasite",
        director: "Bong Joon-ho",
        year: "2019",
        rating: "8.5/10",
        desc: "Keluarga miskin menyusup ke kehidupan keluarga kaya raya.",
        genres: ["Thriller"],
        poster: "resources/parasite.jpg",
        background: "resources/parasiteL.jpg",
        trailer: ""
    },
    {
        id: 45,
        title: "Breaking Bad",
        director: "Vince Gilligan",
        year: "2008",
        rating: "9.5/10",
        desc: "Guru kimia beralih menjadi raja narkoba.",
        genres: ["Thriller"],
        poster: "resources/breakingBad.jpg",
        background: "resources/breakingBadL.jpg",
        trailer: ""
    },
    {
        id: 46,
        title: "Fight Club",
        director: "David Fincher",
        year: "1999",
        rating: "8.8/10",
        desc: "Pria insomnia membentuk klub pertarungan bawah tanah.",
        genres: ["Thriller"],
        poster: "resources/fightClub.jpg",
        background: "resources/fightClubL.jpg",
        trailer: ""
    },
    {
        id: 47,
        title: "More Than Blue",
        director: "Won Tae-yeon",
        year: "2009",
        rating: "7.5/10",
        desc: "Kisah cinta tragis Korea yang menguras air mata.",
        genres: ["K-Drama"],
        poster: "resources/moreThanBlue.jpg",
        background: "resources/moreThanBlueL.jpg",
        trailer: ""
    },
    {
        id: 48,
        title: "Strangers From Hell",
        director: "Lee Chang-hee",
        year: "2019",
        rating: "7.8/10",
        desc: "Penghuni kos misterius yang membuat hidup jadi neraka.",
        genres: ["K-Drama"],
        poster: "resources/strangersFromHell.jpg",
        background: "resources/strangersFromHellL.jpg",
        trailer: ""
    },
    {
        id: 49,
        title: "All About Lily Chou-Chou",
        director: "Shunji Iwai",
        year: "2001",
        rating: "7.5/10",
        desc: "Sisi gelap kehidupan remaja Jepang dan musik ethereal.",
        genres: ["J-Drama"],
        poster: "resources/aalcc.jpg",
        background: "resources/aalccL.jpg",
        trailer: ""
    },
    {
        id: 50,
        title: "If My Wife Becomes an Elementary School Student",
        director: "Toshio Tsuboi",
        year: "2022",
        rating: "7.5/10",
        desc: "Istri yang meninggal bereinkarnasi menjadi anak SD.",
        genres: ["J-Drama"],
        poster: "resources/imwbaess.jpg",
        background: "resources/imwbaessL.jpg",
        trailer: ""
    },
    {
        id: 51,
        title: "Kurosagi",
        director: "Yasuharu Ishii",
        year: "2006",
        rating: "7.4/10",
        desc: "Penipu yang menipu penipu lain.",
        genres: ["J-Drama"],
        poster: "resources/theBlackSwindler.jpg",
        background: "resources/theBlackSwindlerL.jpg",
        trailer: ""
    },
    {
        id: 52,
        title: "Rebooting",
        director: "Itaru Mizuno",
        year: "2008",
        rating: "7.0/10",
        desc: "Drama Jepang tentang kesempatan kedua.",
        genres: ["J-Drama"],
        poster: "resources/rebooting.jpg",
        background: "resources/rebootingL.jpg",
        trailer: ""
    }
];