const allMoviesData = [
    {
      id: 1,
      title: "A Man Called Otto",
      director: "Marc Forster",
      year: 2022,
      rating: "7.5/10",
      desc: "Otto, seorang pria pemarah, menyerah pada kehidupan setelah kehilangan istrinya.",
      genres: ["Comedy"],
      poster: "Asset/PosterFilm/aManCalledOtto.jpg",
      background: "Asset/BackgroundFilm/aManCalledOttoL.jpg"
    },
    {
      id: 2,
      title: "Bullet Train Explosion",
      director: "Shinji Higuchi",
      year: 2025,
      rating: "N/A",
      desc: "Ledakan kereta cepat yang memicu kekacauan besar.",
      genres: ["Action"],
      poster: "Asset/PosterFilm/bulletTrainExplosion.jpg",
      background: "Asset/BackgroundFilm/bulletTrainExplosionL.jpg"
    },
    {
      id: 3,
      title: "The Wild Robot",
      director: "Chris Sanders",
      year: 2024,
      rating: "8.3/10",
      desc: "Petualangan robot yang terdampar di pulau tak berpenghuni.",
      genres: ["Adventure"],
      poster: "Asset/PosterFilm/theWildRobot.jpg",
      background: "Asset/BackgroundFilm/theWildRobotL.jpg"
    },
    {
      id: 4,
      title: "The Truman Show",
      director: "Peter Weir",
      year: 1998,
      rating: "8.2/10",
      desc: "Seorang pria menyadari bahwa seluruh hidupnya adalah acara TV.",
      genres: ["Drama"],
      poster: "Asset/PosterFilm/theTrumanShow.jpg",
      background: "Asset/BackgroundFilm/theTrumanShowL.jpg"
    },
    {
      id: 5,
      title: "Why Didn't I Tell You a Million Times",
      director: "Fuminori Kaneko",
      year: 2023,
      rating: "7.9/10",
      desc: "Kisah cinta dan penyesalan yang melampaui kematian.",
      genres: ["J-Drama"],
      poster: "Asset/PosterFilm/wdityamt.jpg",
      background: "Asset/BackgroundFilm/wdityamtL.jpg"
    },
    {
      id: 6,
      title: "The Green Mile",
      director: "Frank Darabont",
      year: 1999,
      rating: "8.6/10",
      desc: "Keajaiban misterius di blok penjara hukuman mati.",
      genres: ["Mystery"],
      poster: "Asset/PosterFilm/theGreenMile.jpg",
      background: "Asset/BackgroundFilm/theGreenMileL.jpg"
    },
    {
      id: 7,
      title: "Nightcrawler",
      director: "Dan Gilroy",
      year: 2014,
      rating: "7.8/10",
      desc: "Sisi gelap jurnalisme kriminal di Los Angeles.",
      genres: ["Drama"],
      poster: "Asset/PosterFilm/nightcrawler.jpg",
      background: "Asset/BackgroundFilm/nightcrawlerL.jpg"
    },
    {
      id: 8,
      title: "House",
      director: "David Shore",
      year: 2004,
      rating: "8.7/10",
      desc: "Dokter jenius yang memecahkan kasus medis misterius.",
      genres: ["Mystery"],
      poster: "Asset/PosterFilm/house.jpg",
      background: "Asset/BackgroundFilm/houseL.jpg"
    },
    {
      id: 9,
      title: "It",
      director: "Andy Muschietti",
      year: 2017,
      rating: "7.3/10",
      desc: "Teror badut Pennywise menghantui kota Derry.",
      genres: ["Horror"],
      poster: "Asset/PosterFilm/it.jpg",
      background: "Asset/BackgroundFilm/itL.jpg"
    },
    {
      id: 10,
      title: "The Terminal",
      director: "Steven Spielberg",
      year: 2004,
      rating: "7.4/10",
      desc: "Seorang pria terjebak tinggal di bandara JFK.",
      genres: ["Comedy"],
      poster: "Asset/PosterFilm/theTerminal.jpg",
      background: "Asset/BackgroundFilm/theTerminalL.jpg"
    },
    {
      id: 11,
      title: "Lost",
      director: "J.J. Abrams",
      year: 2004,
      rating: "8.3/10",
      desc: "Korban selamat kecelakaan pesawat di pulau misterius.",
      genres: ["Mystery"],
      poster: "Asset/PosterFilm/lost.jpg",
      background: "Asset/BackgroundFilm/lostL.jpg"
    },
    {
      id: 12,
      title: "District 9",
      director: "Neill Blomkamp",
      year: 2009,
      rating: "7.9/10",
      desc: "Alien yang terdampar di bumi dipaksa hidup di daerah kumuh.",
      genres: ["Action"],
      poster: "Asset/PosterFilm/district9.jpg",
      background: "Asset/BackgroundFilm/district9L.jpg"
    },
    {
      id: 13,
      title: "Everything Everywhere All At Once",
      director: "Daniels",
      year: 2022,
      rating: "7.8/10",
      desc: "Petualangan melintasi multiverse untuk menyelamatkan dunia.",
      genres: ["Action"],
      poster: "Asset/PosterFilm/eeaao.jpg",
      background: "Asset/BackgroundFilm/eeaaoL.jpg"
    },
    {
      id: 14,
      title: "The Dark Knight",
      director: "Christopher Nolan",
      year: 2008,
      rating: "9.0/10",
      desc: "Batman menghadapi ancaman anarkis dari Joker.",
      genres: ["Action"],
      poster: "Asset/PosterFilm/theDarkKnight.jpg",
      background: "Asset/BackgroundFilm/theDarkKnightL.jpg"
    },
    {
      id: 15,
      title: "The Matrix",
      director: "The Wachowskis",
      year: 1999,
      rating: "8.7/10",
      desc: "Seorang hacker menemukan kebenaran tentang realitasnya.",
      genres: ["Action"],
      poster: "Asset/PosterFilm/theMatrix.jpg",
      background: "Asset/BackgroundFilm/theMatrixL.jpg"
    },
    {
      id: 16,
      title: "Cowboy Bebop",
      director: "Shinichirō Watanabe",
      year: 1998,
      rating: "8.9/10",
      desc: "Petualangan pemburu hadiah di luar angkasa.",
      genres: ["Anime"],
      poster: "Asset/PosterFilm/cowboyBebop.jpg",
      background: "Asset/BackgroundFilm/cowboyBebopL.jpg"
    },
    {
      id: 17,
      title: "Indiana Jones and The Last Crusade",
      director: "Steven Spielberg",
      year: 1989,
      rating: "8.2/10",
      desc: "Indy mencari ayahnya yang hilang saat mencari Cawan Suci.",
      genres: ["Adventure"],
      poster: "Asset/PosterFilm/indianaJonesAndTheLastCrusade.jpg",
      background: "Asset/BackgroundFilm/indianaJonesAndTheLastCrusadeL.jpg"
    },
    {
      id: 18,
      title: "Wall-E",
      director: "Andrew Stanton",
      year: 2008,
      rating: "8.4/10",
      desc: "Robot pembersih sampah memulai perjalanan antargalaksi.",
      genres: ["Adventure"],
      poster: "Asset/PosterFilm/wallE.jpg",
      background: "Asset/BackgroundFilm/wallEL.jpg"
    },
    {
      id: 19,
      title: "Up",
      director: "Pete Docter",
      year: 2009,
      rating: "8.3/10",
      desc: "Pria tua menerbangkan rumahnya menuju Paradise Falls.",
      genres: ["Adventure"],
      poster: "Asset/PosterFilm/up.jpg",
      background: "Asset/BackgroundFilm/upL.jpg"
    },
    {
      id: 20,
      title: "Free Guy",
      director: "Shawn Levy",
      year: 2021,
      rating: "7.1/10",
      desc: "NPC dalam video game menyadari bahwa ia hidup di dalam game.",
      genres: ["Comedy"],
      poster: "Asset/PosterFilm/free guy.jpg",
      background: "Asset/BackgroundFilm/freeGuyL.jpg"
    },
    {
      id: 21,
      title: "The Intouchables",
      director: "Olivier Nakache",
      year: 2011,
      rating: "8.5/10",
      desc: "Persahabatan unik antara bangsawan lumpuh dan pengasuhnya.",
      genres: ["Comedy"],
      poster: "Asset/PosterFilm/theIntouchables.jpg",
      background: "Asset/BackgroundFilm/theIntouchablesL.jpg"
    },
    {
      id: 22,
      title: "Liar Liar",
      director: "Tom Shadyac",
      year: 1997,
      rating: "6.9/10",
      desc: "Seorang pengacara dikutuk tidak bisa berbohong selama 24 jam.",
      genres: ["Comedy"],
      poster: "Asset/PosterFilm/liarLiar.jpg",
      background: "Asset/BackgroundFilm/liarLiarL.jpg"
    },
    {
      id: 23,
      title: "Whiplash",
      director: "Damien Chazelle",
      year: 2014,
      rating: "8.5/10",
      desc: "Drummer muda didorong hingga batasnya oleh instruktur kejam.",
      genres: ["Drama"],
      poster: "Asset/PosterFilm/whiplash.jpg",
      background: "Asset/BackgroundFilm/whiplashL.jpg"
    },
    {
      id: 24,
      title: "The Social Network",
      director: "David Fincher",
      year: 2010,
      rating: "7.8/10",
      desc: "Kisah berdirinya Facebook dan konflik hukum di baliknya.",
      genres: ["Drama"],
      poster: "Asset/PosterFilm/theSocialNetwork.jpg",
      background: "Asset/BackgroundFilm/theSocialNetworkL.jpg"
    },
    {
      id: 25,
      title: "Better Call Saul",
      director: "Vince Gilligan",
      year: 2015,
      rating: "9.0/10",
      desc: "Transformasi Jimmy McGill menjadi pengacara Saul Goodman.",
      genres: ["Drama"],
      poster: "Asset/PosterFilm/betterCallSaul.jpg",
      background: "Asset/BackgroundFilm/betterCallSaulL.jpg"
    },
    {
      id: 26,
      title: "Scott Pilgrim vs. The World",
      director: "Edgar Wright",
      year: 2010,
      rating: "7.5/10",
      desc: "Scott harus mengalahkan 7 mantan pacar jahat.",
      genres: ["Fantasy"],
      poster: "Asset/PosterFilm/scottPilgrimVsTheWorld.jpg",
      background: "Asset/BackgroundFilm/scottPilgrimVsTheWorldL.jpg"
    },
    {
      id: 27,
      title: "Pan's Labyrinth",
      director: "Guillermo del Toro",
      year: 2006,
      rating: "8.2/10",
      desc: "Dongeng gelap berlatar Spanyol pasca perang sipil.",
      genres: ["Fantasy"],
      poster: "Asset/PosterFilm/pan'sLabyrinth.jpg",
      background: "Asset/BackgroundFilm/pan'sLabyrinthL.jpg"
    },
    {
      id: 28,
      title: "Adventure Time",
      director: "Pendleton Ward",
      year: 2010,
      rating: "8.6/10",
      desc: "Petualangan Finn dan anjing ajaib Jake.",
      genres: ["Fantasy"],
      poster: "Asset/PosterFilm/adventureTime.jpg",
      background: "Asset/BackgroundFilm/adventureTimeL.jpg"
    },
    {
      id: 29,
      title: "Klaus",
      director: "Sergio Pablos",
      year: 2019,
      rating: "8.2/10",
      desc: "Asal usul Santa Claus dalam animasi yang indah.",
      genres: ["Fantasy"],
      poster: "Asset/PosterFilm/klaus.jpg",
      background: "Asset/BackgroundFilm/klausL.jpg"
    },
    {
      id: 30,
      title: "Invincible",
      director: "Robert Kirkman",
      year: 2021,
      rating: "8.7/10",
      desc: "Anak superhero terkuat bumi mulai menemukan kekuatannya.",
      genres: ["Fantasy"],
      poster: "Asset/PosterFilm/invincible.jpg",
      background: "Asset/BackgroundFilm/invincibleL.jpg"
    },
    {
      id: 31,
      title: "Five Nights At Freddy's",
      director: "Emma Tammi",
      year: 2023,
      rating: "5.5/10",
      desc: "Penjaga malam menghadapi robot animatronik yang hidup.",
      genres: ["Horror"],
      poster: "Asset/PosterFilm/fnaf.jpg",
      background: "Asset/BackgroundFilm/fnafL.jpg"
    },
    {
      id: 32,
      title: "Get Out",
      director: "Jordan Peele",
      year: 2017,
      rating: "7.8/10",
      desc: "Kunjungan ke rumah pacar berubah menjadi mimpi buruk.",
      genres: ["Horror"],
      poster: "Asset/PosterFilm/getOut.jpg",
      background: "Asset/BackgroundFilm/getOutL.jpg"
    },
    {
      id: 33,
      title: "Mama",
      director: "Andy Muschietti",
      year: 2013,
      rating: "6.2/10",
      desc: "Dua gadis kecil diasuh oleh entitas misterius.",
      genres: ["Horror"],
      poster: "Asset/PosterFilm/mama.jpg",
      background: "Asset/BackgroundFilm/mamaL.jpg"
    },
    {
      id: 34,
      title: "Godzilla Minus One",
      director: "Takashi Yamazaki",
      year: 2023,
      rating: "8.3/10",
      desc: "Jepang pasca perang menghadapi ancaman Godzilla.",
      genres: ["Horror"],
      poster: "Asset/PosterFilm/godzillaMinusOne.jpg",
      background: "Asset/BackgroundFilm/godzillaMinusOneL.jpg"
    },
    {
      id: 35,
      title: "Prisoners",
      director: "Denis Villeneuve",
      year: 2013,
      rating: "8.1/10",
      desc: "Seorang ayah mencari putrinya yang diculik.",
      genres: ["Mystery"],
      poster: "Asset/PosterFilm/prisoners.jpg",
      background: "Asset/BackgroundFilm/prisonersL.jpg"
    },
    {
      id: 36,
      title: "Harakiri",
      director: "Masaki Kobayashi",
      year: 1962,
      rating: "8.6/10",
      desc: "Kisah samurai tentang kehormatan dan kemiskinan.",
      genres: ["Mystery"],
      poster: "Asset/PosterFilm/harakiri.jpg",
      background: "Asset/BackgroundFilm/harakiriL.jpg"
    },
    {
      id: 37,
      title: "Donnie Darko",
      director: "Richard Kelly",
      year: 2001,
      rating: "8.0/10",
      desc: "Remaja dihantui visi kiamat dari kelinci raksasa.",
      genres: ["Thriller"],
      poster: "Asset/PosterFilm/donnieDarko.jpg",
      background: "Asset/BackgroundFilm/donnieDarkoL.jpg"
    },
    {
      id: 38,
      title: "The Shawshank Redemption",
      director: "Frank Darabont",
      year: 1994,
      rating: "9.3/10",
      desc: "Harapan dan persahabatan di dalam penjara seumur hidup.",
      genres: ["Thriller"],
      poster: "Asset/PosterFilm/elitis.jpg",
      background: "Asset/BackgroundFilm/elitisL.jpg"
    },
    {
      id: 39,
      title: "Parasite",
      director: "Bong Joon-ho",
      year: 2019,
      rating: "8.5/10",
      desc: "Keluarga miskin menyusup ke kehidupan keluarga kaya.",
      genres: ["Thriller"],
      poster: "Asset/PosterFilm/parasite.jpg",
      background: "Asset/BackgroundFilm/parasiteL.jpg"
    },
    {
      id: 40,
      title: "Breaking Bad",
      director: "Vince Gilligan",
      year: 2008,
      rating: "9.5/10",
      desc: "Guru kimia beralih profesi menjadi raja narkoba.",
      genres: ["Thriller"],
      poster: "Asset/PosterFilm/breakingBad.jpg",
      background: "Asset/BackgroundFilm/breakingBadL.jpg"
    },
    {
      id: 41,
      title: "Fight Club",
      director: "David Fincher",
      year: 1999,
      rating: "8.8/10",
      desc: "Pria insomnia membentuk klub pertarungan bawah tanah.",
      genres: ["Thriller"],
      poster: "Asset/PosterFilm/fightClub.jpg",
      background: "Asset/BackgroundFilm/fightClubL.jpg"
    },
    {
      id: 42,
      title: "More Than Blue",
      director: "Won Tae-yeon",
      year: 2009,
      rating: "7.5/10",
      desc: "Kisah cinta tragis yang menguras air mata.",
      genres: ["K-Drama"],
      poster: "Asset/PosterFilm/moreThanBlue.jpg",
      background: "Asset/BackgroundFilm/moreThanBlueL.jpg"
    },
    {
      id: 43,
      title: "Strangers From Hell",
      director: "Lee Chang-hee",
      year: 2019,
      rating: "7.8/10",
      desc: "Neraka di dalam rumah kos yang aneh.",
      genres: ["K-Drama"],
      poster: "Asset/PosterFilm/strangersFromHell.jpg",
      background: "Asset/BackgroundFilm/strangersFromHellL.jpg"
    },
    {
      id: 44,
      title: "All About Lily Chou-Chou",
      director: "Shunji Iwai",
      year: 2001,
      rating: "7.5/10",
      desc: "Sisi gelap kehidupan remaja dan musik ethereal.",
      genres: ["J-Drama"],
      poster: "Asset/PosterFilm/aalcc.jpg",
      background: "Asset/BackgroundFilm/aalccL.jpg"
    },
    {
      id: 45,
      title: "If My Wife Becomes an Elementary School Student",
      director: "Toshio Tsuboi",
      year: 2022,
      rating: "7.5/10",
      desc: "Istri yang bereinkarnasi kembali ke keluarganya.",
      genres: ["J-Drama"],
      poster: "Asset/PosterFilm/imwbaess.jpg",
      background: "Asset/BackgroundFilm/imwbaessL.jpg"
    },
    {
      id: 46,
      title: "Kurosagi",
      director: "Yasuharu Ishii",
      year: 2006,
      rating: "7.4/10",
      desc: "Penipu yang memburu penipu lain.",
      genres: ["J-Drama"],
      poster: "Asset/PosterFilm/theBlackSwindler.jpg",
      background: "Asset/BackgroundFilm/theBlackSwindlerL.jpg"
    },
    {
      id: 47,
      title: "Rebooting",
      director: "Itaru Mizuno",
      year: 2008,
      rating: "7.0/10",
      desc: "Mendapat kesempatan kedua dalam hidup.",
      genres: ["J-Drama"],
      poster: "Asset/PosterFilm/rebooting.jpg",
      background: "Asset/BackgroundFilm/rebootingL.jpg"
    },
    {
      id: 48,
      title: "The Batman",
      director: "Matt Reevers",
      year: 2022,
      rating: "8.5/10",
      desc: "Batman mengungkap korupsi di Gotham City.",
      genres: ["Action"],
      poster: "Asset/PosterFilm/TheBatman.jpg",
      background: "Asset/BackgroundFilm/theBatmanL.jpg"
    },
    {
      id: 49,
      title: "F1 The Movie",
      director: "Joseph Kosinski",
      year: 2025,
      rating: "N/A",
      desc: "Dunia balap Formula 1 yang penuh adrenalin.",
      genres: ["Drama"],
      poster: "Asset/PosterFilm/F1TheMovie.jpg",
      background: "Asset/BackgroundFilm/F1TheMovieL.jpg"
    },
    {
      id: 50,
      title: "Uncharted Movie",
      director: "Ruben Fleischer",
      year: 2022,
      rating: "6.3/10",
      desc: "Pemburu harta karun mencari kekayaan yang hilang.",
      genres: ["Adventure"],
      poster: "Asset/PosterFilm/Uncharted.jpg",
      background: "Asset/BackgroundFilm/UnchartedL.jpg"
    },
    {
      id: 51,
      title: "Haikyu!! The Dumpster Battle",
      director: "Susumu Mitsunaka",
      year: 2024,
      rating: "8.0/10",
      desc: "Pertandingan voli epik di tempat sampah.",
      genres: ["Anime"],
      poster: "Asset/PosterFilm/haikyu-the-dumpster-battle.jpg",
      background: "Asset/BackgroundFilm/haikyu-the-dumpster-battleL.jpg"
    },
    {
      id: 52,
      title: "Agak Laen",
      director: "Muhadkly Acho",
      year: 2024,
      rating: "7.9/10",
      desc: "Komedi horor tentang rumah hantu yang viral.",
      genres: ["Comedy"],
      poster: "Asset/PosterFilm/Agak_Laen_(2024).jpg",
      background: "Asset/BackgroundFilm/Agak_Laen_(2024)L.jpg"
    },
    {
      id: 53,
      title: "Soundtrack #1",
      director: "Kim Hee-won",
      year: 2023,
      rating: "7.8/10",
      desc: "Dua sahabat tinggal bersama dan menemukan cinta.",
      genres: ["Drama"],
      poster: "Asset/PosterFilm/Soundtrack-1.jpg",
      background: "Asset/BackgroundFilm/soundtrack01L.jpg"
    },
    {
      id: 54,
      title: "Migration",
      director: "Benjamin Renner",
      year: 2023,
      rating: "6.7/10",
      desc: "Keluarga bebek bermigrasi ke Jamaika.",
      genres: ["Adventure"],
      poster: "Asset/PosterFilm/Migration.jpg",
      background: "Asset/BackgroundFilm/MigrationL.jpg"
    },
    {
      id: 55,
      title: "Despicable Me 4",
      director: "Chris Renaud",
      year: 2024,
      rating: "6.3/10",
      desc: "Gru dan Minions kembali dengan kekacauan baru.",
      genres: ["Comedy"],
      poster: "Asset/PosterFilm/Despicable-Me-4.jpg",
      background: "Asset/BackgroundFilm/Despicable-Me-4L.jpg"
    },
    {
      id: 56,
      title: "How to Make Millions Before Grandma Dies",
      director: "Pat Boonnitipat",
      year: 2024,
      rating: "8.4/10",
      desc: "Cucu merawat nenek demi warisan, namun menemukan kasih sayang.",
      genres: ["Drama"],
      poster: "Asset/PosterFilm/Before grandma dies.jpg",
      background: "Asset/BackgroundFilm/beforeGrandmaDiesL.jpg"
    },
    {
      id: 57,
      title: "RA. ONE",
      director: "Guy Ritchie",
      year: 2011,
      rating: "6.2/10",
      desc: "Karakter game keluar ke dunia nyata.",
      genres: ["Action"],
      poster: "Asset/PosterFilm/Ra_one.jpg",
      background: "Asset/BackgroundFilm/Ra_oneL.jpg"
    },
    {
      id: 58,
      title: "Otonari no Tenshi-sama",
      director: "Kenichi Imaizumi",
      year: 2023,
      rating: "7.5/10",
      desc: "Kisah cinta manis tetangga apartemen.",
      genres: ["Anime"],
      poster: "Asset/PosterFilm/Otonari-no-Tenshi-Sama.jpg",
      background: "Asset/BackgroundFilm/Otonari-no-Tenshi-SamaL.jpg"
    },
    {
      id: 59,
      title: "Titanic",
      director: "James Cameron",
      year: 1997,
      rating: "7.9/10",
      desc: "Cinta bersemi di kapal yang akan tenggelam.",
      genres: ["Drama"],
      poster: "Asset/PosterFilm/Titanic.jpg",
      background: "Asset/BackgroundFilm/TitanicL.jpg"
    },
    {
      id: 60,
      title: "Transformers One",
      director: "Josh Cooley",
      year: 2024,
      rating: "N/A",
      desc: "Asal usul Optimus Prime dan Megatron.",
      genres: ["Fantasy"],
      poster: "Asset/PosterFilm/transformerOne.jpg",
      background: "Asset/BackgroundFilm/transformerOneL.jpg"
    },
    {
      id: 61,
      title: "Spy X Family Code White",
      director: "Takashi Katagiri.",
      year: 2023,
      rating: "7.2/10",
      desc: "Misi liburan keluarga Forger.",
      genres: ["Anime"],
      poster: "Asset/PosterFilm/Spy_x_Family_Code_White.jpg",
      background: "Asset/BackgroundFilm/SpyxFamilyBackground.jpg"
    }
];